/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aisaka_ffmpegandroid_FFmpegUtil */

#ifndef _Included_com_aisaka_ffmpegandroid_FFmpegUtil
#define _Included_com_aisaka_ffmpegandroid_FFmpegUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aisaka_ffmpegandroid_FFmpegUtil
 * Method:    _dumpFormat
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_aisaka_ffmpegandroid_FFmpegUtil__1dumpFormat
        (JNIEnv *, jobject, jstring);

/*
 * Class:     com_aisaka_ffmpegandroid_FFmpegUtil
 * Method:    _playVideo
 * Signature: (Ljava/lang/String;Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_com_aisaka_ffmpegandroid_FFmpegUtil__1playVideo
        (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_aisaka_ffmpegandroid_FFmpegUtil
 * Method:    playAudioOpenSLES
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_aisaka_ffmpegandroid_FFmpegUtil_playAudioOpenSLES
        (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
