//
// Created by Apple on 2020-03-10.
//

#ifndef PLAYERDEMO_PLAYERSTATUS_H
#define PLAYERDEMO_PLAYERSTATUS_H

#endif //PLAYERDEMO_PLAYERSTATUS_H

#define PLAYER_IDLE 0
#define PLAYER_PREPARED 1
#define PLAYER_PLAYING 2
#define PLAYER_STOP 4
#define PLAYING_SEEKING 5
